import java.util.List;

public enum NaughtyStringType {
    RESERVED_STRINGS(NaughtyStringInternal.RESERVED_STRINGS),
    NUMERIC_STRINGS(NaughtyStringInternal.NUMERIC_STRINGS),
    SPECIAL_CHARACTERS(NaughtyStringInternal.SPECIAL_CHARACTERS),
    UNICODE_SYMBOLS(NaughtyStringInternal.UNICODE_SYMBOLS),
    UNICODE_SUBSCRIPT_SUPERSCRIPT_ACCENTS(NaughtyStringInternal.UNICODE_SUBSCRIPT_SUPERSCRIPT_ACCENTS),
    QUOTATION_MARKS(NaughtyStringInternal.QUOTATION_MARKS),
    TWO_BYTE_CHARACTERS(NaughtyStringInternal.TWO_BYTE_CHARACTERS),
    TWO_BYTE_LETTER(NaughtyStringInternal.TWO_BYTE_LETTER),
    SPECIAL_UNICODE_CHARACTERS_UNION(NaughtyStringInternal.SPECIAL_UNICODE_CHARACTERS_UNION),
    CHANGING_LENGTH_WHEN_LOWERCASE(NaughtyStringInternal.CHANGING_LENGTH_WHEN_LOWERCASE),
    JAPANESE_EMOTICONS(NaughtyStringInternal.JAPANESE_EMOTICONS),
    EMOJI(NaughtyStringInternal.EMOJI),
    REGIONAL_INDICATOR_SYMBOLS(NaughtyStringInternal.REGIONAL_INDICATOR_SYMBOLS),
    UNICODE_NUMBERS(NaughtyStringInternal.UNICODE_NUMBERS),
    RIGHT_TO_LEFT_STRINGS(NaughtyStringInternal.RIGHT_TO_LEFT_STRINGS),
    OGHAM_TEXT(NaughtyStringInternal.OGHAM_TEXT),
    UNICODE_UPSIDE_DOWN(NaughtyStringInternal.UNICODE_UPSIDE_DOWN),
    UNICODE_FONT(NaughtyStringInternal.UNICODE_FONT),
    SCRIPT_INJECTION(NaughtyStringInternal.SCRIPT_INJECTION),
    SQL_INJECTION(NaughtyStringInternal.SQL_INJECTION),
    SERVER_CODE_INJECTION(NaughtyStringInternal.SERVER_CODE_INJECTION),
    COMMAND_INJECTION(NaughtyStringInternal.COMMAND_INJECTION),
    XXE_INJECTION(NaughtyStringInternal.XXE_INJECTION),
    UNWANTED_INTERPOLATION(NaughtyStringInternal.UNWANTED_INTERPOLATION),
    FILE_INCLUSION(NaughtyStringInternal.FILE_INCLUSION),
    CVES_AND_VULNERABILITIES(NaughtyStringInternal.CVES_AND_VULNERABILITIES),
    WINDOWS_SPECIAL_FILENAMES(NaughtyStringInternal.WINDOWS_SPECIAL_FILENAMES),
    IRC_SPECIFIC_STRINGS(NaughtyStringInternal.IRC_SPECIFIC_STRINGS),
    SCUNTHORPE_PROBLEM(NaughtyStringInternal.SCUNTHORPE_PROBLEM),
    HUMAN_INJECTION(NaughtyStringInternal.HUMAN_INJECTION),
    TERMINAL_ESCAPE_CODES(NaughtyStringInternal.TERMINAL_ESCAPE_CODES),
    IOS_VULNERABILITIES(NaughtyStringInternal.IOS_VULNERABILITIES),
    PERSIAN_SPECIAL_CHARACTERS(NaughtyStringInternal.PERSIAN_SPECIAL_CHARACTERS),
    JINJA_2_INJECTION(NaughtyStringInternal.JINJA_2_INJECTION);

    private List<String> items;

    NaughtyStringType(List<String> items) {
        this.items = items;
    }

    public List<String> getString() {
        return items;
    }
}
